name: Python application test with Github Actions

# uncomment when well tested
on: [push]

# trigger it manually
# on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test    
